os: linux
language: python
python:
  - "3.7"

services:
  - docker

before_install:
  # install conda
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # install conda-build
  - conda install -q conda-build
  # build conda recipe
  - conda build -c abailoni -c cpape -c awolny -c conda-forge --python=$TRAVIS_PYTHON_VERSION conda-recipe

before_script:
  # create test env
  - conda create -n plant-seg -c abailoni -c cpape -c awolny -c conda-forge --use-local python=$TRAVIS_PYTHON_VERSION nifty=vplantseg1.0.8 pytorch-3dunet=1.2.5 plantseg
  - conda activate plant-seg
  # install test dependencies
  - conda install pytest

script:
  - pytest -v

before_deploy:
  # install anaconda-client
  - conda install -q anaconda-client

deploy:
  - provider: script
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload $HOME/miniconda/conda-bld/**/plantseg-*.tar.bz2
      && docker build -t plantseg .
      && docker tag plantseg wolny/plantseg:latest
      && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      && sudo docker push wolny/plantseg:latest
    on:
      tags: true
    skip_cleanup: true

env:
  global:
    # encrypted $DOCKER_PASSWORD
    secure: "EZyzHWY4zNnixdl9g6yKcOXwZcxd/iQwBN7k4ZC7D75HZVDgsk/a6jzlPaUAnTlI02trD+Q9HpVty/x1jmALeDBZ2h2WpqA0dLEAMH0n1gcTBjuQv5QfgLj31DuSM1BBFL343oN+ZDxDI6ps366tE/K3xwIv/Q+usmbItofTDrmq8DWRD1a1jrv9yjrkGdeOj0MNys8e5aUm56x5oGOVtPo5yU4tI0CC5YEn9Yff5hByoTYyJ5BUKKL3thAGbgq6i7Ya+6xUwCJpcf2jHwtA6YoL24+zYw+O8aVqaCdVsK61iSYc7SGOliGvTvw6+9FNpIUszNy451maQmoUVLlp7dXSmjsfOMalSpDCgTQlNf9TKHuTfdfQMn9GuFWTYmfMNxD0/nJT4uFQh4PIWju/v8ngFHVrm4QU2ZbNDbgVWfYbf/Lyude4q81GMqGpJHTVimJcrPPbNSlc9pmF8LvWKbtaJny7aa027tptzuxK9WL3LzLINEYHn8prQ+8BvijBPV1C9x/yrez5XAAWI27hJ3tA06KEtoW7qIUGX8L+7PCtZdwxGyjmmTePmpX180amRKtV7YlBTnIgq/VK0YCsmZEH3USgNFQ4y/ngpk3DNT0a3I7PpvEjlDNlpCTGRNJyUx4MHSwoW/vjnCduc7ZMcwOniq89cTtCFTPn3ok9FiA="
