# H5 file structure
gt_name: "label"
seg_name: "segmentation"

# Files location GT files and Segmentation files have to share a single ID number in order to be matched
gt_dir: "/export/home/lcerrone/Datasets/TUM_Ovules_Dataset/Ovules_test_final/" # Path to ground truth  directory files at full resolution or dictionary with tuple of ground truth and segmentation. Files must be h5
seg_dir: "/export/home/lcerrone/Datasets/TUM_Ovules_Dataset/Ovules_test_final/unet_ds2x_bce_gcr/MultiCut/" # (Optional) Path to predicted segmentation files at any resolution. Files must be h5 or tiff

# train_config_file: "/home_sdc/lcerrone_tmp/PycharmProjects/FOR2581-segmentation/TUM-Ovules/networks/FOR_paper_experiments/unet_ds2x/config_train.yml" # (Optional) Path to config file used for experiments
# (Optional) Segmentation Algorithm config file. Empty if it does not exists

# Output
output_csv: "./ds2_mc_gcr.csv" # Path to output CSV file

# Custom notes, for comments not in the training configuration file
metadata: # (Optional)
  segmentation_algorithm: "MultiCut" # Segmentation algorithm
  down_sampling: [1, 2, 2] # For example if there is any down sampling
