# Contains the path to the directory or file to process
path:

preprocessing:
  # enable/disable preprocessing
  state: True
  # create a new sub folder where all results will be stored
  save_directory: "PreProcessing"
  # rescaling the volume is essential for the generalization of the networks. The rescaling factor can be computed as the resolution
  # of the volume at hand divided by the resolution of the dataset used in training. Be careful, if the difference is too large check for a different model.
  factor: [1.0, 1.0, 1.0]
  # the order of the spline interpolation
  order: 2
  # cropping out areas of little interest can drastically improve the performance of plantseg.
  # crop volume has to be input using the numpy slicing convention [b_z:e_z, b_x:e_x, b_y:e_y], where b_zxy is the
  # first point of a bounding box and e_zxy is the second. eg: [:, 100:500, 400:900]
  crop_volume: "[:, :, :]"
  # optional: perform Gaussian smoothing or median filtering on the input.
  filter:
    # enable/disable filtering
    state: False
    # Accepted values: 'gaussian'/'median'
    type: gaussian
    # sigma (gaussian) or disc radius (median)
    filter_param: 1.0

cnn_prediction:
  # enable/disable UNet prediction
  state: True
  # Trained model name, more info on available models and custom models in the README
  model_name: "generic_confocal_3D_unet"
  # If a CUDA capable gpu is available and corrected setup use "cuda", if not you can use "cpu" for cpu only inference (slower)
  device: "cuda"
  # patch size given to the network (adapt to fit in your GPU mem)
  patch: [80, 160, 160]
  # stride between patches will be `patch * stride_ratio` (make sure the patches overlap in order to get smoother prediction maps)
  stride_ratio: 0.75
  # padding to be added to each axis in a given patch in order to avoid checkerboard artifacts
  patch_halo: [2, 4, 4]
  # If "True" forces downloading networks for the online repos
  model_update: False
  # how many subprocesses to use for data loading
  num_workers: 8

cnn_postprocessing:
  # enable/disable cnn post processing
  state: True
  # if True convert to result to tiff
  tiff: False
  output_type: "data_float32"
  # rescaling factor
  factor: [1, 1, 1]
  # spline order for rescaling
  order: 2
  # save raw input in the output prediction file h5 file
  save_raw: False


segmentation:
  # enable/disable segmentation
  state: True
  # Name of the algorithm to use for inferences
  name: "GASP"
  # Segmentation specific parameters here
  # balance under-/over-segmentation; 0 - aim for undersegmentation, 1 - aim for oversegmentation
  beta: 0.6
  # directory where to save the results
  save_directory: "GASP"
  # enable/disable watershed
  run_ws: True
  # use 2D instead of 3D watershed
  ws_2D: True
  # probability maps threshold
  ws_threshold: 0.5
  # set the minimum superpixels size
  ws_minsize: 50
  # sigma for the gaussian smoothing of the distance transform
  ws_sigma: 2.0
  # sigma for the gaussian smoothing of boundary
  ws_w_sigma: 0
  # set the minimum segment size in the final segmentation
  post_minsize: 50

segmentation_postprocessing:
  # enable/disable segmentation post processing
  state: True
  # if True convert to result to tiff
  tiff: False
  # rescaling factor
  factor: [1, 1, 1]
  # spline order for rescaling (keep 0 for segmentation post processing
  order: 0
  # save raw input in the output segmentation file h5 file
  save_raw: False
