# use a fixed random seed to guarantee that when you run the code twice you will get the same outcome
manual_seed: 0
model:
  name: UNet2D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 2
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
loss:
  name: BCEDiceLoss
  skip_last_target: true
optimizer:
  # initial learning rate
  learning_rate: 0.0002
  # weight decay
  weight_decay: 0.00001
# evaluation metric
eval_metric:
  name: BlobsAveragePrecision
  thresholds: [0.4, 0.5, 0.6, 0.7, 0.8]
  metric: 'ap'
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.2
  patience: 8
trainer:
  eval_score_higher_is_better: True
  # path to the checkpoint directory
  checkpoint_dir: '/scratch/wolny/plantseg_2d_networks/root_nuclei/bce_dice_ds2x'
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null
  # how many iterations between validations
  validate_after_iters: 500
  # how many iterations between tensorboard logging
  log_after_iters: 250
  # max number of epochs
  max_num_epochs: 400
  # max number of iterations
  max_num_iterations: 80000
loaders:
  batch_size: 16
  # how many subprocesses to use for data loading
  num_workers: 8
  # path to the raw data within the H5
  raw_internal_path: /raw
  # path to the the label data withtin the H5
  label_internal_path: /label
  # configuration of the train loader
  train:
    # paths to the training datasets
    file_paths:
      - '/g/kreshuk/wolny/Datasets/LateralRoot/nuclei/t00015_s01_uint8_cropped_gt.h5'
      - '/g/kreshuk/wolny/Datasets/LateralRoot/nuclei/t00045_s01_uint8_cropped_gt.h5'

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: FilterSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [1, 170, 170]
      # train stride between patches
      stride_shape: [1, 80, 80]
      # minimum volume of the labels in the patch
      threshold: 0.1
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01

    transformer:
      raw:
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
        - name: BlobsToMask
          append_label: true
          boundary: true
        - name: ToTensor
          expand_dims: false

  # configuration of the val loader
  val:
    # paths to the val datasets
    file_paths:
      - '/g/kreshuk/wolny/Datasets/LateralRoot/nuclei/t00030_s01_uint8_cropped_gt.h5'

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: FilterSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [1, 170, 170]
      # train stride between patches
      stride_shape: [1, 170, 170]
      # minimum volume of the labels in the patch
      threshold: 0.01
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01

    # data augmentation
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: BlobsToMask
          append_label: true
          boundary: true
        - name: ToTensor
          expand_dims: false
